### ISSUE TITLE
Migrate external transaction helpers for legacy bridge type

### ISSUE THREAD

**Issue by stevenkhong** [Switcheo/demex-sdk#10]
### Summary
Move bridge transaction helper clients from legacy js-sdk to the `@demex-sdk/polynetwork` package. 

### Goals
- Retain on `@demex-sdk` the functionality to support legacy bridge.

### Non-goals
- Due to limited support of the bridge in favour of new bridge type, we do not want to devote extra effort to rewrite these clients.

### Tasks
Clients to migrate:
- [ ] [ETHClient](https://github.com/Switcheo/carbon-js-sdk/blob/staging/src/clients/ETHClient.ts)
- [ ] [N3Client](https://github.com/Switcheo/carbon-js-sdk/blob/staging/src/clients/N3Client.ts)
- [ ] [NEOClient](https://github.com/Switcheo/carbon-js-sdk/blob/staging/src/clients/NEOClient.ts)
- [ ] [ZILClient](https://github.com/Switcheo/carbon-js-sdk/blob/staging/src/clients/ZILClient.ts)
