### ISSUE TITLE
Create a fetch wrapper for off-chain services like 

### ISSUE THREAD

**Issue by stevenkhong** [Switcheo/demex-sdk#9]
### Summary
dApps often interact with off-chain services (usually indexers) to retrieve historic chain state. This utility class will serve as foundation for building those query clients.

### Goals
1. Provide basic functionalities for conveniently create query clients for services do not support protobuf.
2. Will be extended by Hydrogen and Insights clients.

### Tasks
- [ ] Create fetch wrapper class in `@demex-sdk/core`
- [ ] Add example on how to use
- [ ] Update `README.md`

**Comment by stevenkhong** [comment]
done on #21. updated issue message to include TODO for Hydrogen and Insights fetch clients.
